application: palpitemegasena
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /static
  static_dir: static

- url: /.*
  script: palpite-megasena.app

